#!/bin/bash

# set -x
trap "exit" INT

OPTION="-checksafety -debug"
MAXJOBS="6"

declare -A SUBDIRS
declare -A SUBDIRS2

SUBDIRS[chacha20/ref/chacha20.jazz]="RSI;RDX"
SUBDIRS2[chacha20/ref/chacha20.jazz]="RDI;RDX"

SUBDIRS[poly1305/avx2/poly1305.japp]="RSI;RDX"
SUBDIRS[poly1305/ref3/poly1305.japp]="RSI;RDX"

SUBDIRS[chacha20/avx2/chacha20.jazz]="RSI;RDX"
SUBDIRS2[chacha20/avx2/chacha20.jazz]="RDI;RDX"


CURJOBS=0
for i in "${!SUBDIRS[@]}"; do
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting ${i}"
  (../jasminc ${OPTION} -safetyparam ${SUBDIRS[$i]} ${i} &> ${i}.res ;
   echo "=> Done ${i}, results" ;
   grep Safety ${i}.res | sed 's/^/  /'
  ) & ((++cur_jobs))
done

for i in "${!SUBDIRS2[@]}"; do
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting ${i}"
  (../jasminc ${OPTION} -safetyparam ${SUBDIRS2[$i]} ${i} &> ${i}.res2 ;
   echo "=> Done (2) ${i}, results" ;
   grep Safety ${i}.res2 | sed 's/^/  /'
  ) & ((++cur_jobs))
done

wait
