#!/bin/bash

# set -x
trap "exit" INT

OPTION="-pipeline -branchpredictor"
OPTIONNAIVE="-pipeline -naivepipeline"
MAXJOBS="3"

declare -A SUBDIRS

SUBDIRS[poly1305/ref3/poly1305.japp]="-safetyparam RSI;RDX" # in;inlen
SUBDIRS[poly1305/avx2/poly1305.japp]="-safetyparam RSI;RDX" # in;inlen

SUBDIRS[chacha20/ref/chacha20.jazz]="-safetyparam RSI;RDX" # plain;len
SUBDIRS[chacha20/avx2/chacha20.jazz]="-safetyparam RSI;RDX" # plain;len

SUBDIRS[aes/aes-ctr-alt.jazz]="-safetyparam RSI;RCX" # inp;len

CURJOBS=0
for i in "${!SUBDIRS[@]}"; do
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting analysis of ${i}"
  (../jasminc ${OPTION} ${SUBDIRS[$i]} ${i} &> ${i}.cost ;
   echo "=> Done ${i}, results" 
  ) & ((++cur_jobs))
done

for i in "${!SUBDIRS[@]}"; do
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting analysis of ${i} (naive)"
  (../jasminc ${OPTIONNAIVE} ${SUBDIRS[$i]} ${i} &> ${i}.cost_naive ;
   echo "=> Done ${i}, results" 
  ) & ((++cur_jobs))
done

wait
