#!/bin/bash

# set -x
trap "exit" INT

OPTION="-checksafety -debug"
MAXJOBS="3"

declare -A SUBDIRS
declare -A SUBDIRS2

SUBDIRS[sct-examples/chacha20/ref/chacha20.jazz]="plain;len"
SUBDIRS2[sct-examples/chacha20/ref/chacha20.jazz]="output;len"

SUBDIRS[sct-examples/poly1305/avx2/poly1305.japp]="in;inlen"
SUBDIRS[sct-examples/poly1305/ref3/poly1305.japp]="in;inlen"

SUBDIRS[sct-examples/chacha20/avx2/chacha20.jazz]="plain;len"
SUBDIRS2[sct-examples/chacha20/avx2/chacha20.jazz]="output;len"


CURJOBS=0
for i in "${!SUBDIRS[@]}"; do
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting ${i}"
  (../jasminc ${OPTION} -safetyparam ${SUBDIRS[$i]} ${i} &> ${i}.res ;
   echo "=> Done ${i}, results" ;
   grep Safety ${i}.res | sed 's/^/  /'
  ) & ((++cur_jobs))
done

for i in "${!SUBDIRS2[@]}"; do
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting ${i}"
  (../jasminc ${OPTION} -safetyparam ${SUBDIRS2[$i]} ${i} &> ${i}.res2 ;
   echo "=> Done (2) ${i}, results" ;
   grep Safety ${i}.res2 | sed 's/^/  /'
  ) & ((++cur_jobs))
done

wait
