(* -------------------------------------------------------------------- *)
(* EasyCrypt model of the Jasmin instructions shared by the Arm
   architectures.

   32-bit operations whose semantics coincide on AArch32 (arm-m4) and
   AArch64 (armv8a W forms), size-suffixed as generated by the armv8a
   extraction. JModel_m4 re-exports this file and abbreviates the bare
   AArch32 names (ADD = ADD_32, ...); JModel_armv8a re-exports it next to
   the 64-bit (X form) operations.

   The operations that differ between the two architectures stay in their
   respective files: the flag-setting logical and shift instructions
   (AArch32 sets NZC with the shifter carry, AArch64 clears C and V), the
   shifts (AArch32 uses the low byte of the amount up to 255, AArch64
   reduces it modulo the operand size) and the extensions (AArch32 takes a
   rotation). *)
require import AllCore List Bool IntDiv.
require export JModel_common JArray JWord_array JMemory JLeakage Jslh.

(* -------------------------------------------------------------------- *)
(* Flags of the flag-setting arithmetic instructions. *)

op nzcv (r: W32.t) (u s: int) : bool * bool * bool * bool =
  (W32.msb r,
   r = W32.zero,
   to_uint r <> u,
   to_sint r <> s).

abbrev with_nzcv r u s =
  let (n, z, c, v) = nzcv r u s in
  (n, z, c, v, r).

(* -------------------------------------------------------------------- *)
(* Arithmetic. *)

op ADDS_32 (x y: W32.t) : bool * bool * bool * bool * W32.t =
  let r = x + y in
  with_nzcv r (to_uint x + to_uint y) (to_sint x + to_sint y).
op ADD_32 x y = let (_n, _z, _c, _v, r) = ADDS_32 x y in r.

op ADCS_32 (x y: W32.t) (c: bool) : bool * bool * bool * bool * W32.t =
  let r = x + y + if c then W32.one else W32.zero in
  with_nzcv r (to_uint x + to_uint y + b2i c) (to_sint x + to_sint y + b2i c).
op ADC_32 x y c = let (_n, _z, _c, _v, r) = ADCS_32 x y c in r.

op SUBS_32 (x y: W32.t) : bool * bool * bool * bool * W32.t =
  ADCS_32 x (invw y) true.
op SUB_32 x y = let (_n, _z, _c, _v, r) = SUBS_32 x y in r.

op SBCS_32 (x y: W32.t) (c: bool) : bool * bool * bool * bool * W32.t =
  ADCS_32 x (invw y) c.
op SBC_32 x y c = let (_n, _z, _c, _v, r) = SBCS_32 x y c in r.

op MUL_32 (x y: W32.t) : W32.t = x * y.

op SDIV_32 (x y: W32.t) : W32.t = x \sdiv y.
op UDIV_32 (x y: W32.t) : W32.t = x \udiv y.

(* -------------------------------------------------------------------- *)
(* Comparisons. *)

op CMN_32 (x y: W32.t) : bool * bool * bool * bool =
  let r = x + y in
  nzcv r (to_uint x + to_uint y) (to_sint x + to_sint y).

op CMP_32 (x y: W32.t) : bool * bool * bool * bool =
  let r = x - y in
  nzcv r (to_uint x - to_uint y) (to_sint x - to_sint y).

(* -------------------------------------------------------------------- *)
(* Logical (results; the flag-setting forms are architecture-specific). *)

op AND_32 (x y: W32.t) : W32.t = andw x y.
op BIC_32 (x y: W32.t) : W32.t = andw x (invw y).
op ORR_32 (x y: W32.t) : W32.t = orw x y.
op EOR_32 (x y: W32.t) : W32.t = x +^ y.
op MVN_32 (x: W32.t) : W32.t = invw x.

(* -------------------------------------------------------------------- *)
(* Moves. *)

op MOV_32 (x: W32.t) : W32.t = x.

(* -------------------------------------------------------------------- *)
(* Bit field operations. *)

op BFC_32 (x: W32.t) (lsb width: W8.t) : W32.t =
  let lsbit = to_uint lsb in
  let msbit = lsbit + to_uint width - 1 in
  W32.init (fun i => if lsbit <= i <= msbit then false else x.[i]).

op BFI_32 (x y: W32.t) (lsb width: W8.t) : W32.t =
  let lsbit = to_uint lsb in
  let msbit = lsbit + to_uint width - 1 in
  W32.init (fun i => if lsbit <= i <= msbit then y.[i - lsbit] else x.[i]).

op SBFX_32 (x: W32.t) (i j: W8.t) : W32.t =
  let k = 32 - to_uint j in
  (x `<<<` (k - to_uint i)) `|>>>` k.

op UBFX_32 (x: W32.t) (i j: W8.t) : W32.t =
  let k = 32 - to_uint j in
  (x `<<<` (k - to_uint i)) `>>>` k.

(* -------------------------------------------------------------------- *)
(* Bit manipulation. *)

op CLZ_32 (x: W32.t) : W32.t =
  W32.of_int (lzcnt (rev (w2bits x))).

op REV_32 (x : W32.t) : W32.t = W4u8.pack4 (rev (W4u8.to_list x)).

op REV_16 (x:W16.t) : W16.t = W2u8.pack2 (rev (W2u8.to_list x)).
op REV16_32 (x : W32.t) : W32.t = W2u16.map REV_16 x.

(* -------------------------------------------------------------------- *)
(* Loads and stores. The memory access itself is part of the Jasmin
   semantics; these operators only extend the transferred value. *)

op LDR_32 (x: W32.t) : W32.t = x.
op LDRB_32 (x: W8.t) : W32.t = W32.of_int (W8.to_uint x).
op LDRH_32 (x: W16.t) : W32.t = W32.of_int (W16.to_uint x).
op LDRSB_32 (x: W8.t) : W32.t = W32.of_int (W8.to_sint x).
op LDRSH_32 (x: W16.t) : W32.t = W32.of_int (W16.to_sint x).

op STR_32 (x: W32.t) : W32.t = x.
op STRB_32 (x: W8.t) : W8.t = x.
op STRH_32 (x: W16.t) : W16.t = x.
