(* Parameters of the semantics of Jasmin.

We need to balance granularity not to introduce unnecessary dependencies while
packing parameters that always go together.

Another concern is that some of these definitions are extracted and used in
OCaml.
Having record fields of type [Type] is inconvenient in OCaml, so we have them
as parameters.
*)

Require Import
  flag_combination
  sopn
  type
  syscall
  wsize.


(* Parameters needed to build states.
   This gets extracted and used in OCaml (in the evaluator), so we have
   [syscall_state] as a parameter instead of a record field. *)
Class EstateParams (syscall_state : Type) := mk_ep
  {
    _pd : PointerData;
    _msf_size : MSFsize;
  }.

#[global]
Existing Instances _pd _msf_size | 1000.

Arguments mk_ep {_ _}.

(* Parameters needed to evaluate expressions. *)
Class SemPexprParams := mk_spp
  {
    _fcp : FlagCombinationParams;
  }.

#[global]
Existing Instance _fcp | 1000.

Arguments mk_spp {_}.


(* Parameters needed to execute programs.
   This gets extracted and used in OCaml (in the evaluator), so [asm_op] and
   [syscall_state] are parameters instead of record fields. *)
Class SemInstrParams (asm_op syscall_state : Type) := mk_sip
  {
    _asmop : asmOp asm_op;
    _sc_sem : syscall_sem syscall_state;
  }.

#[global]
Existing Instances _asmop _sc_sem | 1000.

Arguments mk_sip {_ _ _ _}.

Class WithAssert := { assert_allowed : bool }.
Definition noassert : WithAssert := {| assert_allowed := false |}.
Definition withassert : WithAssert := {| assert_allowed := true |}.

#[global] Existing Instances noassert | 1000.

(* Switch between the two semantics of unsafe operations:
   - when [false] (the default, [nocatch]), an out-of-bound array access, an
     invalid memory access, a division by zero, ... makes the execution fail;
   - when [true] ([withcatch]), such a failure is caught and the operation
     returns a default value instead. [ErrType] is never caught: it denotes an
     ill-typed program, not the violation of a safety property.

   [withcatch] is the semantics of the programs extracted to EasyCrypt, where
   every operator is total. It is what makes the safety conditions generated by
   the safety pass meaningful: [eand] is strict, so proving
   [0 <= i < n /\ 0 <= a[i] < m] requires evaluating [a[i]] even when [i] is out
   of bound. *)
Class WithCatch := { with_catch : bool }.
Definition nocatch : WithCatch := {| with_catch := false |}.
Definition withcatch : WithCatch := {| with_catch := true |}.

(* [nocatch] is the default instance, so every existing development keeps the
   semantics it had.  A proof that needs to compute through a [catch] (typically
   before a [t_xrbindP], which does not see through the [if]) has to reduce the
   instance away with

     rewrite /exec_sopn /with_catch /nocatch ...

   Unfolding is used rather than a rewriting lemma [catch = id] on purpose: the
   latter leaves the goal in a shape [t_xrbindP] handles differently. *)
#[global] Existing Instances nocatch | 1000.
