#!/bin/sh

set -e

DIR=$(mktemp -d jasminXXXXXX)
ASM=${DIR}/jasmin.s
OBJ=${DIR}/jasmin.o

trap "rm -r ${DIR}" EXIT

set -x

$(dirname $0)/../jasminc -g -arch risc-v -o ${ASM} "$@"

llvm-mc --triple=riscv32 --mcpu=generic-rv32 --filetype=obj -o ${OBJ} ${ASM}
