#!/usr/bin/env bash

set -e

ROOT_DIR=tests/results/check-arm-m4
TEST_FILE="${@: -1}"
# Concatenate all args (except test file name - last arg)
ARGS_CAT=args-$(
	IFS=""
	echo "${*:1:$#-1}"
)
DIR=$ROOT_DIR/${TEST_FILE%.jazz}/$ARGS_CAT
ASM=${DIR}/jasmin.s
OBJ=${DIR}/jasmin.o

if [ -d "${DIR}" ]; then rm -r ${DIR}; fi
mkdir -p $DIR

set -x

$(dirname $0)/../jasminc -g -arch arm-m4 -o ${ASM} "$@"
# Negative test cases should have failed by now
# Succeed early if it's not the case (i.e., do not try to assemble the result)
(echo "$@" | grep -q fail) && exit 0

llvm-mc --triple=armv7m --mcpu=cortex-m4 --filetype=obj -o ${OBJ} ${ASM}
