#!/bin/sh

set -e

DIR=$(mktemp -d jasminXXXXXX)
ASM=${DIR}/jasmin.s
OBJ=${DIR}/jasmin.o
DLL=${DIR}/jasmin.so

trap "rm -r ${DIR}" EXIT

set -x

$(dirname $0)/../jasminc -g -o ${ASM} "$@"
# Negative test cases should have failed by now
# Succeed early if it’s not the case (i.e., do not try to assemble the result)
(echo $@ | grep -q fail) && exit 0

cc -c -o ${OBJ} ${ASM}

# Compile as a shared library
# Add an implementation of Jasmin syscalls to avoid “undefined reference” errors
if grep -q __jasmin_syscall ${ASM}
then
	EXT=${DIR}/sys.o
	cc -c -o ${EXT} $(dirname $0)/../syscall/jasmin_syscall.c
else
	EXT=""
fi

cc -shared -o ${DLL} ${OBJ} ${EXT}
