#!/usr/bin/env bash

set -e

# User defined assembly checker binary or llvm-mc
# for macos homebrew install : export ASSEMBLY_CHECKER=riscv64-unknown-elf-as
ASSEMBLY_CHECKER=${ASSEMBLY_CHECKER:-llvm-mc}
# User defined assembly checker options or default for linux
# for macos homebrew install : export ASSEMBLY_CHECKER_OPTIONS=" "
ASSEMBLY_CHECKER_OPTIONS=${ASSEMBLY_CHECKER_OPTIONS:---triple=riscv32 --mcpu=generic-rv32 --mattr=+m --filetype=obj}

ROOT_DIR=tests/results/check-risc-v
TEST_FILE="${@: -1}"
# Concatenate all args (except test file name - last arg)
ARGS_CAT=args-$(
	IFS=""
	echo "${*:1:$#-1}"
)
DIR=$ROOT_DIR/${TEST_FILE%.jazz}/$ARGS_CAT
ASM=${DIR}/jasmin.s
OBJ=${DIR}/jasmin.o

if [ -d "${DIR}" ]; then rm -r ${DIR}; fi
mkdir -p $DIR

set -x

$(dirname $0)/../jasminc -g -arch riscv -o ${ASM} "$@"
# Negative test cases should have failed by now
# Succeed early if it's not the case (i.e., do not try to assemble the result)
(echo "$@" | grep -q fail) && exit 0

${ASSEMBLY_CHECKER} ${ASSEMBLY_CHECKER_OPTIONS} -o ${OBJ} ${ASM}
