#!/bin/sh

set -e

DIR=$(mktemp -d jasminXXXXXX)
ASM=${DIR}/jasmin.s
OBJ=${DIR}/jasmin.o
DLL=${DIR}/jasmin.so

trap "rm -r ${DIR}" EXIT

set -x

$(dirname $0)/../jasminc.native -o ${ASM} "$@"
cc -c -o ${OBJ} ${ASM}
cc -shared -o ${DLL} ${OBJ}
