#!/bin/sh

set -e

DIR=$(mktemp -d jasminXXXXXX)
ASM=${DIR}/jasmin.s
OBJ=${DIR}/jasmin.o
DLL=${DIR}/jasmin.so
# FIXME syscall : how the remove the relative path 
JASMINLIB=../syscall/jasmin_syscall.o
trap "rm -r ${DIR}" EXIT

set -x

$(dirname $0)/../jasminc.native -o ${ASM} "$@"
# Negative test cases should have failed by now
# Succeed early if it’s not the case (i.e., do not try to assemble the result)
(echo $@ | grep -q fail) && exit 0

cc -c -o ${OBJ} ${ASM}
cc -shared -o ${DLL} ${JASMINLIB} ${OBJ}
