#!/usr/bin/env bash

set -e

ROOT_DIR=tests/results/extraction
DIR=$ROOT_DIR/${2%.jazz}/$1
ECLIB=$(dirname $0)/../../eclib
EC=${DIR}/jasmin.ec
CT=${DIR}/jasmin_ct.ec
CTG=${DIR}/jasmin_ctg.ec

if [ -d "${DIR}" ]; then rm -r ${DIR}; fi
mkdir -p $DIR

if [ "$1" = "arm" ]; then
	ARCH="--arch=arm-m4"
elif [ "$1" = "riscv" ]; then
	ARCH="--arch=riscv"
else
	ARCH="--arch=x86-64"
fi

set -x
set -o xtrace

$(dirname $0)/../jasmin2ec ${ARCH} -o ${EC} "$2"
$(dirname $0)/../jasmin2ec ${ARCH} -o ${CT} -m CT "$2"
$(dirname $0)/../jasmin2ec ${ARCH} -o ${CTG} -m CTG "$2"

easycrypt -I Jasmin:${ECLIB} ${ECARGS} ${EC}
easycrypt -I Jasmin:${ECLIB} ${ECARGS} ${CT}
easycrypt -I Jasmin:${ECLIB} ${ECARGS} ${CTG}
