#!/bin/sh

set -e

DIR=$(mktemp -d jasminXXXXXX)
EC=${DIR}/jasmin.ec
CT=${DIR}/jasmin_ct.ec

if [ "$1" = "arm" ]
then
	shift
	ARCH="-arch arm-m4"
else
	ARCH="-arch x86-64"
fi

trap "rm -r ${DIR}" EXIT

set -x

$(dirname $0)/../jasminc ${ARCH} -oecarray ${DIR} -oec ${EC} "$@"
$(dirname $0)/../jasminc ${ARCH} -oecarray ${DIR} -CT -oec ${CT} "$@"

easycrypt ${ECARGS} ${EC}
easycrypt ${ECARGS} ${CT}
