#! /usr/bin/env python3

# --------------------------------------------------------------------
import sys, os, subprocess as sp

# --------------------------------------------------------------------
def _log(msg = ''):
    print(msg, file = sys.stderr)

# --------------------------------------------------------------------
def _run(filename):
    success = False

    _log("### Testing `%s':" % (filename,))
    try:
        rc = sp.call(['./jasminc.native', '-typeonly', filename])
        success = (rc == 0)
    except OSError as e:
        _log("### Cannot start jasmin: %s" % (e,))
    _log("### End testing `%s':" % (filename,))

    return success

# --------------------------------------------------------------------
def _check(filenames):
    errors = []

    for filename in filenames:
        if not _run(filename):
            errors.append(filename)

    if errors:
        _log()
        _log('### Failing files (%d)' % (len(errors)))
        for errf in errors:
            _log('### %s' % (errf,))

    sys.exit(1 if errors else 0)

# --------------------------------------------------------------------
if __name__ == '__main__':
    _check(sys.argv[1:])
