#! /usr/bin/env python2

# --------------------------------------------------------------------
import sys, os, subprocess as sp

# --------------------------------------------------------------------
def _run(filename):
    success = False

    print >>sys.stderr, "### Testing `%s':" % (filename,)
    try:
        rc = sp.call(['./jasminc.native', filename])
        success = (rc == 0)
    except OSError as e:
        print >>sys.stderr, "### Cannot start jasmin: %s" % (e,)
    print >>sys.stderr, "### End testing `%s':" % (filename,)

    return success

# --------------------------------------------------------------------
def _check(filenames):
    errors = []

    for filename in filenames:
        if not _run(filename):
            errors.append(filename)

    if errors:
        print >>sys.stderr
        print >>sys.stderr, '### Failing files (%d)' % (len(errors),)
        for errf in errors:
            print >>sys.stderr, '### %s' % (errf,)

    sys.exit(1 if errors else 0)

# --------------------------------------------------------------------
if __name__ == '__main__':
  _check(sys.argv[1:])
