#!/usr/bin/env bash

set -e

ROOT_DIR=tests/results/parse-print-parse
TEST_FILE=${@: -1}
DIR=$ROOT_DIR/${2%.jazz}/$1
OUT=${DIR}/jasmin.jazz

if [ -d "${DIR}" ]; then rm -r ${DIR}; fi
mkdir -p $DIR

if [ "$1" = "arm" ]
then
    ARCH="-arch arm-m4"
else
    ARCH="-arch x86-64"
fi

set -x

# Check that no printer crashes
$(dirname $0)/../jasminc ${ARCH} -pall "$2" >/dev/null
# Pretty-print the program before compilation
$(dirname $0)/../jasminc ${ARCH} -ptyping "$2" > ${OUT}
# Try to parse it and type-check it again
$(dirname $0)/../jasminc ${ARCH} -until_typing ${OUT}
