#!/bin/bash

# set -x
trap "exit" INT

OPTION="-checksafety -debug"
LIBJCPATH="/home/akoutsos/workspace/research/jasmin/libjc/"
MAXJOBS="3"

declare -A SUBDIRS

SUBDIRS[crypto_onetimeauth/poly1305/ref3]="in;inlen"
SUBDIRS[crypto_onetimeauth/poly1305/avx]="in;inlen"
SUBDIRS[crypto_onetimeauth/poly1305/avx2]="in;inlen"
SUBDIRS[crypto_stream/chacha20/ref]="output;len|plain;len"
SUBDIRS[crypto_stream/chacha20/avx]="output;len|plain;len"
SUBDIRS[crypto_stream/chacha20/avx2]="output;len|plain;len"
SUBDIRS[crypto_scalarmult/curve25519/ref4]=";"
SUBDIRS[crypto_scalarmult/curve25519/mulx]=";"

CURJOBS=0
for i in "${!SUBDIRS[@]}"; do
  mkdir -p ${i} 
  cp ${LIBJCPATH}/src/${i}/*.japp ${i}/in.japp
  # If true, wait until the next background job finishes to continue.
  ((cur_jobs >= MAXJOBS)) && wait -n
  echo "Starting ${i}"
  (../jasminc ${OPTION} -safetyparam ${SUBDIRS[$i]} ${i}/in.japp &> ${i}/out.res ;
   echo "=> Done ${i}, results" ;
   grep Safety ${i}/out.res | sed 's/^/  /'
  ) & ((++cur_jobs))
done

wait
