regs = {} 
regs["r0"] = "r0"
regs["r1"] = "r1"
regs["r2"] = "r2"
regs["r3"] = "r3"
regs["r4"] = "r4"
regs["r5"] = "r5"
regs["r6"] = "r6"
regs["r7"] = "r7"
regs["r8"] = "r8"
regs["r9"] = "r9"
regs["r10"] = "r10"
regs["r11"] = "r11"
regs["r12"] = "r12"
regs["lr"] = "lr"
regs["sp"] = "sp"

arm_conds = {}
arm_conds["EQ_ct"] = "eq"
arm_conds["NE_ct"] = "ne"
arm_conds["CS_ct"] = "cs"
arm_conds["CC_ct"] = "cc"
arm_conds["MI_ct"] = "mi"
arm_conds["PL_ct"] = "pl"
arm_conds["VS_ct"] = "vs"
arm_conds["VC_ct"] = "vc"
arm_conds["HI_ct"] = "hi"
arm_conds["LS_ct"] = "ls"
arm_conds["GE_ct"] = "ge"
arm_conds["LT_ct"] = "lt"
arm_conds["GT_ct"] = "gt"
arm_conds["LE_ct"] = "le"


ops_two_args                = {}
ops_two_args["CLZ"]         = "CLZ"
ops_two_args["CMP"]         = "CMP"
ops_two_args["CMN"]         = "CMN"
ops_two_args["MOV"]         = "MOV"
ops_two_args["MVN"]         = "MVN"
ops_two_args["REV"]         = "REV"
ops_two_args["REV16"]       = "REV16"
ops_two_args["REVSH"]       = "REVSH"
ops_two_args["TST"]         = "TST"
ops_two_args["UXTB"]        = "UXTB"
ops_two_args["UXTH"]        = "UXTH"

ops_three_args              = {}
# Arithmetic
ops_three_args["ADD"]       = "ADD"
ops_three_args["ADC"]       = "ADC"
ops_three_args["MUL"]       = "MUL"
# ops_three_args["SDIV"]      = "SDIV"
# ops_three_args["UDIV"]      = "UDIV"
ops_three_args["SUB"]       = "SUB"
ops_three_args["RSB"]       = "RSB"
ops_three_args["SMMUL"]     = "SMMUL"
ops_three_args["SMMULR"]    = "SMMULR"
ops_three_args["SMULBB"]    = "SMULBB"
ops_three_args["SMULBT"]    = "SMULBT"
ops_three_args["SMULTB"]    = "SMULTB"
ops_three_args["SMULTT"]    = "SMULTT"
ops_three_args["SMULWB"]    = "SMULWB"
ops_three_args["SMULWT"]    = "SMULWT"
#Logical
ops_three_args["AND"]       = "AND"
ops_three_args["BIC"]       = "BIC"
ops_three_args["EOR"]       = "EOR"
ops_three_args["ORR"]       = "ORR"
#Shifts
ops_three_args["ASR"]       = "ASR"
ops_three_args["LSL"]       = "LSL"
ops_three_args["LSR"]       = "LSR"
ops_three_args["ROR"]       = "ROR"

ops_four_args               = {}
ops_four_args["UMAAL"]      = "UMAAL"
ops_four_args["UMLAL"]      = "UMLAL"
ops_four_args["UMULL"]      = "UMULL"