#! /bin/bash

${SED:-sed} -ibak \
  -e "s/Inria/<Anonymized>/i" \
	-e "s/IMDEA Software Institute/<Anonymized>/i" \
  -e "s,http://jasmin-lang.github.io/,http://example.com,i" \
  -e "s,https://github.com/jasmin-lang/jasmin/issues,http://example.com,i" \
  jasmin/proofs/*/*.v jasmin/compiler/src/*.ml* jasmin/compiler/opam
